apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terrabutler-template
  title: Terrabutler Template
  description: A Terrabutler Template template for deploying projects in terrafom.
spec:
  owner: backstage/techdocs-core
  type: service

parameters:
  - title: Choose a location
    required:
      - repoUrl
    properties:
      repoUrl:
        title: Repository Location
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          allowedHosts:
            - github.com
  - title: Fill in some steps
    required:
      - name
      - owner
    properties:
      name:
        title: Name
        type: string
        description: Unique name of the component
        ui:autofocus: true
        ui:options:
          rows: 5
      owner:
        title: Component Owner
        type: string
        description: Owner of the component
        ui:field: OwnerPicker
        ui:options:
          catalogFilter:
            kind: Group
            
  
      
        
steps:
  - id: fetch-base
    name: Fetch Template
    action: fetch:template
    input:
      url: ./template
      values:
        name: ${{ parameters.name }}
        owner: ${{ parameters.owner }}
        
  - id: fetch-project
    name: Fetch Project Files
    action: fetch:project
    input:
      url: .
      values:
        region_var: ${{ parameters.region_var }}
        organization_var: ${{ parameters.organization_var }}
        environment_var: ${{ parameters.environment_var }}
        domain_var: ${{ parameters.domain_var }}
        
  - id: fetch-docs
    name: Fetch Docs
    action: fetch:plain
    input:
      targetPath: ./community
      url: https://github.com/backstage/community/tree/main/backstage-community-sessions
  - id: publish
    name: Publish
    action: publish:github
    input:
      allowedHosts:
        - github.com
      description: This is ${{ parameters.name }}
      repoUrl: ${{ parameters.repoUrl }}
  - id: register
    name: Register
    action: catalog:register
    input:
      repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
      catalogInfoPath: /catalog-info.yaml
