name: Check terraform file formatting

on: [push]

jobs:
  check_format:
    runs-on: ubuntu-22.04
    name: Check terraform file are formatted correctly
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
